# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(100F14)
$foreground = rgb(F6F0F9)
$color0 = rgb(38383C)
$color1 = rgb(0A0B18)
$color2 = rgb(0A0B18)
$color3 = rgb(232E66)
$color4 = rgb(70465A)
$color5 = rgb(5F76AA)
$color6 = rgb(AC9EB3)
$color7 = rgb(EAE1EF)
$color8 = rgb(A39DA7)
$color9 = rgb(0E0E20)
$color10 = rgb(0E0E20)
$color11 = rgb(2E3D88)
$color12 = rgb(955E78)
$color13 = rgb(7E9DE2)
$color14 = rgb(E5D3EF)
$color15 = rgb(EAE1EF)
